server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: leyou126
    password: leyou
    virtual-host: /leyou126
ly:
  sms:
    accessKeyID: LsssssA # 你自己的accessKeyId
    accessKeySecret: f9ZJxxxxxxxxxxxK # 你自己的AccessKeySecret
    signName: 李腾飞自己做短信测试 # 签名名称
    verifyCodeTemplate: SMS_94700095 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id
    code: checkcode # 短信模板中验证码的占位符