server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: leyou126
    password: leyou126
    virtual-host: /leyou126
ly:
  sms:
    accessKeyID: LTAI4FworD3BckZiNQHacojG # 你自己的accessKeyId
    accessKeySecret: d6wRNSugFic56o5xMEgjs91ovpUWpK # 你自己的AccessKeySecret
    signName: 乐友商城    # 签名名称
    verifyCodeTemplate: SMS_186598538 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id
    code: code # 短信模板中验证码的占位符