server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyID: LTAI4FdFNjz9GNw8YqAZRVsD # 阿里云创建用户的accessKeyId
    accessKeySecret: 1JBq6tc3AkTRvPF8iTVKRHoyKoRzRj # 阿里云创建用户的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_186613197 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id
    code: code # 短信模板中验证码的占位符