#配置数据源
sharding:
  jdbc:
    datasource:
      #数据库名，名称不能包含下划线
      names: sharding0,sharding1
      sharding0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/sharding0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
      sharding1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/sharding1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
    config:
      props:
        sql:
          show: true #显示最终sql语句
      sharding:
        #分库策略；行表达式分片策略
        default-database-strategy:
          inline:
            #分库字段；
            sharding-column: order_id
            # 策略；确定数据进入哪个库
            algorithm-expression: sharding$->{order_id%2}
        tables:
          # 分表策略
          tb_order:
            #数据库表节点
            actual-data-nodes: sharding$->{0..1}.tb_order_$->{1..3}
            # 分表策略
            table-strategy:
              inline:
                # 分表字段
                sharding-column: order_id
                # 策略；确定数据进入哪张表
                algorithm-expression: tb_order_$->{order_id%3 + 1}
            # 主键
            key-generator-column-name: order_id
            key-generator-column-class: SNOWFLAKE

spring:
  main:
    allow-bean-definition-overriding: true