server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    username: leyou126
    password: leyou
    virtual-host: /leyou126
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  static:
    itemDir: D:\ly_guangzhou126\software\nginx-1.16.0\html\item #静态页服务器地址
    itemTemplate: item #模板名称